### ISSUE TITLE
Packet capture data

### ISSUE THREAD

**Issue by dcousens** [jpwsutton/instax_api#1]
I recently captured some interaction with my Instax using a [Remote Virtual Interface](https://developer.apple.com/library/content/qa/qa1176/_index.html).
Namely,  I printed out two different photos of different resolutions (as per their source images),  but noted that the resultant image sent was fixed size.

Is it worth posting the PCAP files here for inspection?

**Comment by dorkmatt** [comment]
Yes!

**Comment by dcousens** [comment]
@dorkmatt :(,  someone just referenced me some relevant sections of Australian copyright law,  and I'm not sure where I sit with this now... sigh.

**Comment by jpwsutton** [comment]
@dcousens That's a shame, out of interest do you have a link to those sections? It would be interesting to have a look to see if there is any way around this.

**Comment by dcousens** [comment]
I'm mostly looking at https://www.legislation.gov.au/Details/C2016C00741,
> Part III—Copyright in original literary, dramatic, musical and artistic works
>> 47D  Reproducing computer programs to make interoperable products

The general web has a lot of out-dated content,  many of which don't seem to account for 47D in recent times.
An interpretation in http://www.austlii.edu.au/au/journals/ANZCompuLawJl/2001/7.pdf, pg 30 seems to allude that previous, similar, blackbox cases would be null and void due to the lack of any literary work given the updated legislation... but,  IANAL?

**Comment by dcousens** [comment]
I think it should be OK, since the resulting product/work is purely intended to inter-operate with the original product (the Instax SP-2)...

**Comment by dcousens** [comment]
I don't have this data any more,  but if I find it I'll probably post it :+1:
