### ISSUE TITLE
tuple index out of range with SP-2

### ISSUE THREAD

**Issue by bserem** [jpwsutton/instax_api#11]
I tried to print using the latest version from pip and an SP-2 printer.
The image was saved with a 600x800 pixel resolution (don't really know if this is required).
I am getting the following error:
```
instax-print -v 2 BSRM2001.JPG 
--- Instax Printer Python Client ---

Connecting to Printer.
Model: SP-2
Firmware: 01.21
Battery State: 3
Prints Remaining: 7
Total Lifetime Prints: 17

Printing Image: BSRM2001.JPG
Traceback (most recent call last):
  File "/usr/local/bin/instax-print", line 110, in <module>
    instaxImage.convertImage()
  File "/usr/local/lib/python3.6/dist-packages/instax/instaxImage.py", line 103, in convertImage
    self.myImage = pure_pil_alpha_to_color_v2(newImage, (255,255,255))
  File "/usr/local/lib/python3.6/dist-packages/instax/instaxImage.py", line 268, in pure_pil_alpha_to_color_v2
    background.paste(image, mask=image.split()[3])  # 3 is the alpha channel
IndexError: tuple index out of range
```

At the very same moment I am trying with SP-3 and an image of 3646x3646 pixel resolution.
Prints fine, results are excellent.
```
 $ instax-print -v 3 BSRM2231.JPG 
--- Instax Printer Python Client ---

Connecting to Printer.
Model: SP-3
Firmware: 01.02
Battery State: 3
Prints Remaining: 8
Total Lifetime Prints: 22

Printing Image: BSRM2231.JPG
[============================================================] 100.0% ...Print is complete!                          
Thank you for using instax-print!

        \   /\
        )  ( ')
        (  /  )
         \(___)|
```
(love the cat, or whatever that is)

Is it possible that v3 commits broke v2 or is the driver expecting something different from me?

**Comment by bserem** [comment]
Will test it soon.

**Comment by bserem** [comment]
@shrewmus your suggestion worked fine in my case too for v2. Thanks!
I haven't tried print to v3 with the changed file at the moment.

@jpwsutton do you me to try and prepare a PR?

**Comment by Ennochiantapestry** [comment]
I'm having the same issue and this resolved it. Just to clarify for others experiencing this:
I changed the line of code in the file 'instaxImage.py' from
background.paste(image, mask=image.split()[3])  # 3 is the alpha channel
to
background.paste(image)

and it works!!
