### ISSUE TITLE
constraint with 10 prints

### ISSUE THREAD

**Issue by shrewmus** [jpwsutton/instax_api#14]
I'm trying to increase the printer's capacity and found that printer stops when 10 prints were passed.
Does anyone try the same?
Can I set "Prints Remaining: 0" programmatically?
Is there any API that doesn't in the current release?

**Comment by jpwsutton** [comment]
I've not seen anything in the client side API that would allow us to do that, so I think that it might be hard coded into the printer's firmware.

I've absolutely no idea how one would go about this, but as the Android and iPhone apps can flash the printer with new firmware, it might be possible to extract the current firmware bin, decompile, mod the limit and recompile it, then re-flash it onto a printer... That would most certainly invalidate the warranty though and would probably be quite difficult..

**Comment by shrewmus** [comment]
I close this issue - I've put two additional relays. One on the case door switch, one on the cartridge switch. And emulate sequence - open case, take off cartridge, place cartridge, close case via relays.
