### ISSUE TITLE
Reprint button programmable?

### ISSUE THREAD

**Issue by v0-llc** [jpwsutton/instax_api#18]
Just curious - any idea if pressing the "reprint" button on the Instax printer broadcasts a message that could be intercepted / used to do something different? Or is the functionality hard coded and only local to the device?
Thanks.

**Comment by jpwsutton** [comment]
From my experience, it's a function that is hard coded within the printers firmware so can't be hooked into from the client side.

Technically, it's not impossible to extract the firmware bin from the APK, I've no idea how one would go about reverse engineering and modifying it though, which you would need to do if you wanted to change what that button does. If you do go down that route though, I'd be interested to see how you get on!

**Comment by v0-llc** [comment]
@jpwsutton Thanks for that info - that's what I figured.
That definitely sounds like an interesting avenue to explore, but almost certainly more time than we're willing to invest at this point!
We had thought about using the button to trigger a script to run the print command, but in the end just went with a wired Arduino / USB button solution.
Thanks again for your insight!
