### ISSUE TITLE
Question: Instax or Local WIFI ?

### ISSUE THREAD

**Issue by JpEncausse** [jpwsutton/instax_api#19]
The library must be installed on a device connected directly to the Instax Wifi ? 
It's not possible to connect the Instax to the Home Wifi then send print action throught that wifi ?

**Comment by jpwsutton** [comment]
Hi @JpEncausse, Unfortunately the Instax SP range is only designed to host it's own network which you connect to. (This is based around the original purpose which is to be connected to from a mobile app or compatible Fujifilm camera).

It should be technically possible to enable a client AP mode through the firmware, but someone would have to reverse engineer the firmware to enable this and I'm nowhere near being able to do this yet.
