### ISSUE TITLE
Preview before print?

### ISSUE THREAD

**Issue by bserem** [jpwsutton/instax_api#22]
I've been using this tool for more than a year now and I am loving it so far.

I face one very common issue though: on SP3 a lot of times my photos are being printed rotated by 90/-90 degrees. I see them just fine on my computer (with Gimp or Geeqie on Linux) so I go on and print them only to get a rotated print.

I was wonder if it would be possible to add a preview functionality before printing, even with some flag that would not result in a print (eg: `instax-print -v 2 --preview FILE.JPG` that would work even without a printer connected).

Could something like this be possible?
Thanks

**Comment by jpwsutton** [comment]
This sounds pretty straightforward, in fact I think that there is some code hidden inside the image scaling / rotating functions that lets us do this. I'll have a look this evening and see if I can get something working.

**Comment by jpwsutton** [comment]
Ok, this was even easier than I thought, so I did it in my lunch break 😄 . I've added the --preview argument. When you use it, the client will scale and orient the image as best it can, then will open it using your OS's default image viewer and will exit.

Have a pull of the code from github and let me know what you think @bserem

**Comment by bserem** [comment]
It works very very nice!!

I tried it *without* a printer connected, both on square and portait images and I could see the images fine (with imagemagick viewer for reasons I do not know, but it doesn't matter).

I could preview orientation:
`instax-print -v 2 --preview beatrice-wong_75_africa_09.jpg`
![image](https://user-images.githubusercontent.com/520237/83021589-e50f1000-a032-11ea-9e5b-e1b79e662e99.png)
(Image by Beatrice Wong)

and top/bottom white border:
`instax-print -v 2 --preview bin_zhang_65_dreamy_scenery_02.jpg`
![image](https://user-images.githubusercontent.com/520237/83021762-2c959c00-a033-11ea-82d6-58af2ed5ed13.png)
(Image by Bin Zhang)

**Comment by jpwsutton** [comment]
Awesome, I'll push this in the next version that goes on to pypi!
