### ISSUE TITLE
It Works! (Kind of)

### ISSUE THREAD

**Issue by jpwsutton** [jpwsutton/instax_api#3]
Ok, so the code still needs a lot of work and is quite messy right now... However I did just print out a photo from my mac!

![firsteverphoto](https://user-images.githubusercontent.com/1068763/31587282-ed88fe3c-b1d6-11e7-9a02-8eb5fe39ab21.jpg) (Incase you were wondering, the model is my pair programming buddy)

So, how do you print photos today?

1. Download this repository and follow the instructions in the readme to setup the virtualenv environment.
2. Edit [newEx.py](https://github.com/jpwsutton/instax_api/blob/master/newEx.py) to change [line 15](https://github.com/jpwsutton/instax_api/blob/a130f7510b135c55f2d571940ff9c6fdc19ee0eb/newEx.py#L15) to point at the photo you would like to print.
3. Turn on your Instax SP2 printer
4. Connect to it's Wifi SSID (Usually INSTAX-*) where the * is the first part of the MAC address of the device.
5. Run `python3 newEx.py`.

Currently, I'm dumping a load of debug to the console, and the final bit of the process that checks the status of the print isn't working (It will throw an exception). But with that in mind, it should still print! YMMV, but if anything interesting happens, feel free to raise an issue. 

For now, I'm going to tidy up the project and get rid of anything that's now unnecessary, as well as try and fix the print status code. Then I'll write a proper cli application where you can use cli arguments and switches to define the photo to print as well as showing previews etc..

**Comment by jpwsutton** [comment]
@dcousens @dorkmatt - Apologies for taking almost a year to get it this far, but almost done!

**Comment by dorkmatt** [comment]
Awesome, will check this out this week - thanks!

**Comment by dcousens** [comment]
@jpwsutton awesome work!

**Comment by lippling** [comment]
@jpwsutton This is great!!

**Comment by easy221707N1140927E** [comment]
@jpwsutton Thanks very much for your great work!

Any advice, please? I've got the following errors when trying to instax-print on my MacBook pro:

File "/usr/local/bin/instax-print", line 4, in <module>
    __import__('pkg_resources').run_script('instax-api==0.1', 'instax-print')
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 742, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 1666, in run_script
    code = compile(source, script_filename, 'exec')
  File "/Library/Python/2.7/site-packages/instax_api-0.1-py2.7.egg/EGG-INFO/scripts/instax-print", line 56
    print = myInstax.printPhoto(encodedImage)

**Comment by jpwsutton** [comment]
@easy221707N1140927E Sorry, this library is only compatible with Python 3 (and I've only tested with Python 3.4 and above).

You should have python 3 available on your mac, if you remove it using `sudo pip uninstall instax-api` (assuming you installed it via pip) and then do `sudo pip3 install instax-api` then it should work for you.

I'll update the readme to show the Python 3 dependency.
