### ISSUE TITLE
Polaroid Now+

### ISSUE THREAD

**Issue by dmitrizzle** [jpwsutton/instax_api#32]
Hello,

I'm a total Noob when it comes to making software that connects to devices. But I wonder if anyone here can answer this for me: **is it possible to write a similar API for Polaroid Now+ cameras?** They have a Bluetooth interface that connects with their app which can control the camera's exposure and other settings (but the camera itself is 100% analogue, i.e., it exposes film to light directly).

Thanks so much and sorry if I'm breaking the flow here.

**Comment by dtgreene** [comment]
Should be possible for sure but the reverse engineering work is pretty hardware specific. I.e. you’d need to mostly start from scratch for a new device. I’m working on a similar project for the Canon Ivy 2 which is a Bluetooth mini photo printer.

**Comment by dmitrizzle** [comment]
I've never hacked hardware, but it's good to know it's feasible. I know Polaroid has an app that already controls their analogue camera's physical aperture/shutter speed but I'd love to make a more suitable interface. I really wish they just had an API... Would've been fun.

Thank you for your answer @dtgreene! If you have any resources I could get started on, please let me know.

**Comment by dtgreene** [comment]
For sure! I actually just got everything working yesterday.  Here's the project -> https://github.com/dtgreene/ivy2 

I'm still working on a document that goes over the process I used but it was basically a matter of de-compiling the Android app and piecing together the correct messages to send to the printer. I might have a go at this one as well while I'm still on the reverse-engineering train
