### ISSUE TITLE
Wiki not public

### ISSUE THREAD

**Issue by julian-w** [jpwsutton/instax_api#5]
There are some references to wiki pages, but the wiki is not accessible. Could you please make the wiki public accessible? Thank you!

**Comment by jpwsutton** [comment]
Hi,

The Wiki used to be mostly just full off random notes that I wrote whilst trying to work out how the protocol worked and isn't really relevant / accurate any more so I deleted it. I'll go through the rest of the repo and remove the old references, but will see if I can add any extra useful information into the README somewhere.

**Comment by jpwsutton** [comment]
I should have closed this a while ago, the wiki is publicly available now.
